import { AntiqueItem } from './types';

export const MOCK_ANTIQUES: AntiqueItem[] = [
  {
    id: '1',
    name: 'Victorian Velvet Armchair',
    price: 1250,
    category: 'Furniture',
    era: 'Late 19th Century',
    description: 'A meticulously restored mahogany armchair upholstered in deep emerald velvet.',
    history: 'Crafted around 1885 in London, this chair features the characteristic cabriole legs of the late Victorian revival period. It was originally part of a set owned by a merchant family in Kensington.',
    image: 'https://picsum.photos/id/102/800/800', // Using generic placeholders for demo
  },
  {
    id: '2',
    name: 'Ming Dynasty Style Vase',
    price: 3400,
    category: 'Ceramics',
    era: 'Early 20th Century Replica',
    description: 'A high-quality blue and white porcelain vase depicting traditional mountain landscapes.',
    history: 'While not an original Ming artifact, this early 20th-century piece from the Republic period demonstrates exceptional kiln mastery, likely from Jingdezhen.',
    image: 'https://picsum.photos/id/200/800/800',
  },
  {
    id: '3',
    name: 'Brass Telescope',
    price: 895,
    category: 'Scientific Instruments',
    era: '1910s',
    description: 'Solid brass refracting telescope with original leather wrapping and wooden tripod.',
    history: 'Used by maritime navigators in the North Atlantic, this piece bears the mark of Cooke, Troughton & Simms. It retains its original optics with surprising clarity.',
    image: 'https://picsum.photos/id/400/800/800',
  },
  {
    id: '4',
    name: 'Art Deco Vanity Mirror',
    price: 550,
    category: 'Decor',
    era: '1920s',
    description: 'Geometric frameless mirror with silver backing and etched floral details.',
    history: 'A quintessential Jazz Age piece, likely manufactured in France. The geometric etching reflects the fascination with Cubism and machinery during the Roaring Twenties.',
    image: 'https://picsum.photos/id/300/800/800',
  },
  {
    id: '5',
    name: 'Oak Apothecary Cabinet',
    price: 2100,
    category: 'Furniture',
    era: '1905',
    description: 'Large oak cabinet with 24 distinct drawers, original brass label holders intact.',
    history: 'Salvaged from a pharmacy in rural Pennsylvania, this cabinet was used to store medicinal herbs and compounds. The wood has developed a rich, honey-colored patina.',
    image: 'https://picsum.photos/id/500/800/800',
  },
  {
    id: '6',
    name: 'Silver Pocket Watch',
    price: 420,
    category: 'Jewelry',
    era: '1890s',
    description: 'Sterling silver mechanical pocket watch with visible escapement and Roman numerals.',
    history: 'Produced by the Waltham Watch Company, this timepiece was a standard for railroad conductors who required absolute precision.',
    image: 'https://picsum.photos/id/600/800/800',
  },
];
